#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 yi-protect contributors
#
# Build this boot's lower-half bring-up from the camera's own stock script.
# The stock hardware bring-up (wifi, gpio, mounts) runs unchanged; only the
# vendor application launch is replaced by ours. Regenerated on every boot so
# it always matches the camera the SD card is in and its current firmware.
#
# Usage: gen-lower-half.sh STOCK OUT
# Exit 0 only if every edit landed and OUT passes `sh -n`; otherwise OUT is
# not written and the caller should run STOCK unmodified.

YIP_PREFIX=/tmp/sd/yi-protect
STOCK="$1"
OUT="$2"

[ -f "$STOCK" ] && [ -n "$OUT" ] || exit 1

# Stock launch block: the dispatch line ("dispatch&", "./dispatch &", ...) up to
# the watch_process line (same variants). The aging-test block's own dispatch is
# skipped; log_tools' "exit" is commented out.
awk -v P="$YIP_PREFIX" '
NR == 1 {
    if ($0 !~ /^#!/) { bad = 1 }
    print
    print "# run-once guard (generated by gen-lower-half.sh)"
    print "if [ -f /tmp/init_started ]; then exit; fi"
    print "touch /tmp/init_started"
    next
}
/^if .*factory_aging_test\.sh/ { in_factory = 1 }
in_factory && /^fi[ \t]*$/ { in_factory = 0 }
/log_tools\.tar\.gz/ { in_log = 1 }
in_log && /^[ \t]*exit[ \t]*$/ { print "#" $0; next }
in_log && /^fi[ \t]*$/ { in_log = 0 }
/^[ \t]*(\.\/)?dispatch[ \t]*&[ \t]*$/ && !in_factory && !launched {
    print "# yi-protect launch (generated by gen-lower-half.sh)"
    print "mount --bind " P "/script/wifidhcp.sh /home/app/script/wifidhcp.sh"
    print "mount --bind " P "/script/wifidhcp.sh /backup/tools/wifidhcp.sh"
    print "mount --bind " P "/script/ethdhcp.sh /home/app/script/ethdhcp.sh"
    print "mount --bind " P "/script/ethdhcp.sh /backup/tools/ethdhcp.sh"
    print "LD_PRELOAD=" P "/lib/ipc_multiplex.so ./dispatch &"
    launched = 1
    in_launch = 1
}
in_launch {
    print "#" $0
    if ($0 ~ /^[ \t]*(\.\/)?watch_process[ \t]*&[ \t]*$/) { in_launch = 0; closed = 1 }
    next
}
{ print }
END {
    print ""
    print "chmod 755 " P "/script/init.sh"
    print "sh " P "/script/init.sh &"
    exit (bad || !launched || !closed)
}' "$STOCK" > "$OUT.tmp" || { rm -f "$OUT.tmp"; exit 1; }

sh -n "$OUT.tmp" || { rm -f "$OUT.tmp"; exit 1; }
mv "$OUT.tmp" "$OUT"
